@startuml flowchart
start

:Login Admin;
if (Kelola Gudang?) then (Ya)
  :Tambah Gudang;
  :Perbarui Informasi Gudang;
  :Hapus Gudang;
else
  if (Kelola Barang?) then (Ya)
    :Tambah Barang;
    :Perbarui Barang;
    :Hapus Barang;
  else
    if (Pantau Barang?) then (Ya)
      :Pindai Barcode;
      :Cari Secara Manual;
    else
      if (Buat Laporan?) then (Ya)
        :Laporan Stok Barang;
        :Kebutuhan Restocking;
      endif
    endif
  endif
endif

stop
@enduml
